### ISSUE TITLE
NavigationBar has a background color when using the Modal component on Android

### ISSUE THREAD

**Issue by mydesweb** [zoontek/react-native-edge-to-edge#25]
### Why it is needed?

Modal component has a property `statusBarTranslucent ` which works, but there is no option to control the Navigation bar.. there is any way to make also Navigation bar translucent?

**Comment by zoontek** [comment]
Not as I know, but I highly recommend using [`react-navigation` modals](https://reactnavigation.org/docs/modal/) instead.

**Comment by baghel-rohan** [comment]
That is exactly the same issue I am also facing.

react-native: 0.71.14,
react-native-bars: 2.4.2, (previously: 1.1.2 still same issue on both versions),
react-native-bootsplash: 4.7.5,

I would, If I could color the navigation bar white but this is how it looks when modal is open

<img width="405" alt="Screenshot 2024-02-02 at 11 18 36 AM" src="https://github.com/zoontek/react-native-bars/assets/124653077/ff711df4-ead6-4a3c-aa7d-f3819b578193">

I can manage the status bar, but there should be a prop to handle the background color of the navigation bar, on the go.

Thanks for just reading it all, I would be thankful if it could actually be done.

great library RNbootsplash though 👍

**Comment by zoontek** [comment]
@baghel-rohan This is actually impossible to do from this library as react-native uses a `Dialog` for `Modal` (and so, a different context that the one we can access in react native module).

That's also why [these kind of issues](https://github.com/facebook/react-native/issues/37801) occurs and why it have a [`statusBarTranslucent`](https://reactnative.dev/docs/modal#statusbartranslucent-android) property (as it doesn't care about the main activity status / navigation bar transparency - [link here](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java#L199))

Until there's a solution in React Native for that, I highly recommend using [react navigation modals](https://reactnavigation.org/docs/modal/).

**Comment by baghel-rohan** [comment]
Hi @zoontek, Thank you for the response, and I really like your work!! 

There is another approach to the library which can be implemented, if user wants to, i.e. not using it in edge to edge mode. 

I would like to propose a feature which can allow a background color that will be used in navigation bar and status bar if the user is not using library to implement edge to edge.

I have cloned and implemented this on my end, and would like you to see if you would want to intergrate it with the library.

Below is the video after implementing this approach.
[untitled.webm](https://github.com/zoontek/react-native-bars/assets/124653077/0b8d6b54-3a17-479c-b6bb-265d410e6c6b)

**Comment by zoontek** [comment]
Unfortunately that's not what I want to achieve with this library.

Android is currently the only platform that bother devs with opaque bars, even if they push against, see the SplashScreen API that is edge-to-edge on system thread or the improved keyboard navigation that only works when the UI is edge-to-edge, but uh…legacy. We continue to support versions as old as Android 5 when Android 14.

Opaque bars must die 😄

**Comment by zoontek** [comment]
This quirk is now explained [in the README](https://github.com/zoontek/react-native-edge-to-edge/blob/main/README.md#modal-component-quirks)
