### ISSUE TITLE
Initial SystemBars style

### ISSUE THREAD

**Issue by mydesweb** [zoontek/react-native-edge-to-edge#30]
### Why it is needed?

In the past we had these options:
`RNBars.init(this, "dark-content");`
and
`<item name="darkContentBarsStyle">true</item>`
now they are missing.

**Comment by zoontek** [comment]
@mydesweb This is not required anymore. You can use `android:windowLightStatusBar` (https://github.com/zoontek/react-native-edge-to-edge/blob/67280e4afa64029db0b5798626715da732a1897a/android/src/main/java/com/zoontek/rnedgetoedge/RNEdgeToEdgeModuleImpl.kt#L57)
