### ISSUE TITLE
No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"

### ISSUE THREAD

**Issue by dppo** [zoontek/react-native-edge-to-edge#40]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

I have added `.web.mjs` in extensions, but for some reason, it still enters `dist/index.mjs`

### Library version

1.1.5

### Environment info

```shell
✘ [ERROR] No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"

    node_modules/react-native-is-edge-to-edge/dist/index.mjs:1:19:
      1 │ import { Platform, TurboModuleRegistry } from 'react-native';
        ╵                    ~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce

✘ [ERROR] No matching export in "node_modules/react-native-web/dist/index.js" for import "TurboModuleRegistry"

    node_modules/react-native-is-edge-to-edge/dist/index.mjs:1:19:
      1 │ import { Platform, TurboModuleRegistry } from 'react-native';
        ╵                    ~~~~~~~~~~~~~~~~~~~

### Reproducible sample code

```js
import react-native-is-edge-to-edge in web
```

**Comment by zoontek** [comment]
> Library version
> 1.1.5

`1.1.6` is available [and probably fix the issue](https://github.com/zoontek/react-native-edge-to-edge/blob/main/react-native-is-edge-to-edge/CHANGELOG.md#116).

Bootsplash and keyboard-controller, the libraries relying on it are both been updated to use `1.1.6` already.
