### ISSUE TITLE
SystemBars throws errors on web

### ISSUE THREAD

**Issue by awinograd** [zoontek/react-native-edge-to-edge#48]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

`setImmediate` is not available on the web platform. Using it in `SystemBars` causes any usage of the component to throw errors when targeting the web platform.

### Library version

1.1.2

### Environment info

```shell
expo sdk 52
react-native-web 19.x
```

### Steps to reproduce

1. Render `<SystemBars />` in a react-native-web project

### Reproducible sample code

```js
`return <SystemBars />`
```

**Comment by zoontek** [comment]
Fixed in [1.1.3](https://github.com/zoontek/react-native-edge-to-edge/releases/tag/1.1.3)
