### ISSUE TITLE
Option to disable 3-button background

### ISSUE THREAD

**Issue by flipflop97** [zoontek/react-native-edge-to-edge#49]
### Why it is needed?

When using the 3-button layout instead of the gesture one, it seems to draw a background behind the buttons. For apps that use a static and solid color, this is unnecessary and would look better without the background.

Example where a white background is drawn, and no background would look better:

<img width="404" alt="image" src="https://github.com/user-attachments/assets/88d74b2e-2d28-4695-997e-52f2c0ccbddf">

### Possible implementation

[setNavigationBarContrastEnforced](https://developer.android.com/reference/android/view/Window#setNavigationBarContrastEnforced(boolean)) seems to be able to do this

**Comment by zoontek** [comment]
@flipflop97 This is not how Android 15 performs (when targetting SDK 35 - edge-to-edge is enforced):

![Screenshot 2024-11-29 at 11 42 49](https://github.com/user-attachments/assets/b225a561-4b2f-4ed3-83d8-ba8bc16912a0)

The goal here is to align with Android behavior, nothing more.

I personally understand why Google choosed that way, as having `setNavigationBarContrastEnforced` set to `false` delegates navigation bar style handling to the developer, which is another burden, just to handle a fraction of users (Android users that actively disabled gesture navigation - now the default).
