### ISSUE TITLE
Breaks iOS auto colored status bar

### ISSUE THREAD

**Issue by flipflop97** [zoontek/react-native-edge-to-edge#50]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

Prior to using this library, iOS build would automatically change the status bar color based on the background, just like the navigation bar on both Android and iOS does. However, after setting up this library, the status bar is always colored statically (based on dark mode). It would be very useful to get the auto coloring back when using this library.

### Library version

1.1.3

### Environment info

```shell
System:
  OS: macOS 15.1.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 219.98 MB / 32.00 GB
  Shell:
    version: 3.7.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 22.11.0
    path: ~/.nvm/versions/node/v22.11.0/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v22.11.0/bin/npm
  Watchman:
    version: 2024.11.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 23.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: 15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Reproducible sample code

Should be in any app, but can be seen when changing contrast behind the status bar in iOS

**Comment by zoontek** [comment]
@flipflop97 `SystemBars` aligns with [`expo-status-bar`](https://docs.expo.dev/versions/latest/sdk/status-bar/#style), for a consistant behavior between Android and iOS.

It you want a platform specific behavior, you can wrap it in a custom component with:

```tsx
<SystemBars
  style={Platform.OS === "ios" ? undefined : style}
  // …
```

An option to have truly automatic bar style (based on contrast) might be added if at some point the feature is also available on Android.
